version: "3"

services:
  producer:
    build: .
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    networks:
      - my-network
    image: producer:latest

networks:
  my-network:
    external: true