version: "3"

services:
  web:
    build: .
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"     # Run the FastAPI app
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/app         # Mount local ./html directory to Nginx HTML directory