apiVersion: v1
kind: Service
metadata:
  name: k8s-key-value-store-service
spec:
  selector:
    app: k8s-key-value-store
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
