version: "3"

services:
  consumer:
    build: .
    ports:
      - 8002:8002
    volumes:
      - .:/app
    networks:
      - my-network
    image: chaitraboggaram/k8s-key-value-store-consumer:latest

networks:
  my-network:
    external: true