apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: consumer-pod
  template:
    metadata:
      labels:
        app: consumer-pod
    spec:
      containers:
      - name: consumer
        image: chaitraboggaram/k8s-key-value-store:consumer
