apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: producer
        image: chaitraboggaram/k8s-key-value-store:producer
      ports:
      - containerPort: 8000